///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace sq1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the sq1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("97904eb2-bb19-4994-8501-d17ec8209b85")]
    public partial class sq1Repository : RepoGenBaseFolder
    {
        static sq1Repository instance = new sq1Repository();

        /// <summary>
        /// Gets the singleton class instance representing the sq1Repository element repository.
        /// </summary>
        [RepositoryFolder("97904eb2-bb19-4994-8501-d17ec8209b85")]
        public static sq1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public sq1Repository() 
            : base("sq1Repository", "/", null, 0, false, "97904eb2-bb19-4994-8501-d17ec8209b85", ".\\RepositoryImages\\sq1Repository97904eb2.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("97904eb2-bb19-4994-8501-d17ec8209b85")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class sq1RepositoryFolders
    {
    }
#pragma warning restore 0436
}
